version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./backend:/app/backend
    environment:
      - DATABASE_URL=sqlite:///./sql_app.db
      - SECRET_KEY=your-secret-key-here
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
      - ./uploads:/app/uploads
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - API_URL=http://backend:8000/api/v1
      - DOCKER_ENV=true
    networks:
      - app-network
    command: streamlit run frontend/app.py

networks:
  app-network:
    driver: bridge 